"""tb_catalog_exec_change_table_name_and_column_name_change_to_perfume_id

Revision ID: 0a06e829d578
Revises: c179efb24a95
Create Date: 2026-02-27 14:31:13.185234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a06e829d578'
down_revision: Union[str, Sequence[str], None] = 'c179efb24a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_catalog',
    sa.Column('perfume_id', sa.Integer(), nullable=False),
    sa.Column('perfume', sa.String(length=128), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=128), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('perfume_id')
    )
    op.drop_table('catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('perfume', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('imagem_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('catalog_pkey'))
    )
    op.drop_table('tb_catalog')
    # ### end Alembic commands ###
