"""Nome da tabela corrigido

Revision ID: 1ff52ef7f8f7
Revises: 59d0a40b1c42
Create Date: 2026-01-09 15:06:59.685820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff52ef7f8f7'
down_revision: Union[str, Sequence[str], None] = '59d0a40b1c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lorenci')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lorenci',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('perfume', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('imagem_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Lorenci_pkey'))
    )
    # ### end Alembic commands ###
