"""Incluindo novo campo de imagem_url para catalogo

Revision ID: 3b4f17be1155
Revises: 4a3bc05ecf2d
Create Date: 2025-12-03 14:34:41.485943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4f17be1155'
down_revision: Union[str, Sequence[str], None] = '4a3bc05ecf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('imagem_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'imagem_url')
    # ### end Alembic commands ###
