"""tb_usuario_exec_changes

Revision ID: 4060addae700
Revises: 0a06e829d578
Create Date: 2026-03-02 10:43:25.724949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4060addae700'
down_revision: Union[str, Sequence[str], None] = '0a06e829d578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types if they don't exist (with exception handling)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE user_types AS ENUM ('customer', 'admin');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE sexo_types AS ENUM ('M', 'F');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    op.create_table('tb_usuario',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hash_senha', sa.String(
                        length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.Column('tipo_usuario', postgresql.ENUM('customer', 'admin',
                                                              name='user_types', create_type=False), nullable=False),
                    sa.Column('nome', sa.String(length=128), nullable=False),
                    sa.Column('sexo', postgresql.ENUM('M', 'F', name='sexo_types',
                                                      create_type=False), nullable=True),
                    sa.Column('cpf', sa.String(length=11), nullable=False),
                    sa.Column('numero_tel', sa.String(
                        length=15), nullable=True),
                    sa.Column('cep', sa.String(length=10), nullable=True),
                    sa.Column('rua', sa.String(length=128), nullable=True),
                    sa.Column('numero_residencia',
                              sa.Integer(), nullable=True),
                    sa.Column('cidade', sa.String(length=128), nullable=True),
                    sa.Column('uf', sa.String(length=2), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cpf'),
                    sa.UniqueConstraint('email')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('user', postgresql.ENUM('customer', 'admin', name='user_types',
                                                      create_type=False), autoincrement=False, nullable=False),
                    sa.Column('nome', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('sexo', postgresql.ENUM('M', 'F', name='sexo_types',
                                                      create_type=False), autoincrement=False, nullable=True),
                    sa.Column('cpf', sa.VARCHAR(length=11),
                              autoincrement=False, nullable=False),
                    sa.Column('numero_tel', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('cep', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('rua', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=True),
                    sa.Column('numero', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('cidade', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=True),
                    sa.Column('uf', sa.VARCHAR(length=2),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
                    sa.UniqueConstraint('cpf', name=op.f('user_cpf_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False),
                    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
