"""tb_fornecedor_changes_razao_social

Revision ID: 44855e7e816a
Revises: 8e6249e37efa
Create Date: 2026-03-02 14:33:24.428059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44855e7e816a'
down_revision: Union[str, Sequence[str], None] = '8e6249e37efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column as nullable first to allow data migration
    op.add_column('tb_fornecedor', sa.Column(
        'razao_social', sa.String(length=128), nullable=True))

    # Migrate data from old column to new column
    op.execute("UPDATE tb_fornecedor SET razao_social = razao")

    # Now make the column NOT NULL after data is migrated
    op.alter_column('tb_fornecedor', 'razao_social', nullable=False)

    op.drop_column('tb_fornecedor', 'razao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add old column as nullable first to allow data migration
    op.add_column('tb_fornecedor', sa.Column('razao', sa.VARCHAR(
        length=128), autoincrement=False, nullable=True))

    # Migrate data back from new column to old column
    op.execute("UPDATE tb_fornecedor SET razao = razao_social")

    # Now make the column NOT NULL after data is migrated
    op.alter_column('tb_fornecedor', 'razao', nullable=False)

    op.drop_column('tb_fornecedor', 'razao_social')
    # ### end Alembic commands ###
