"""Alterado tipo de dado do CPF

Revision ID: 4a3bc05ecf2d
Revises: 
Create Date: 2025-11-25 23:39:10.980627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a3bc05ecf2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'cpf',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'cpf',
               existing_type=sa.String(length=11),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
