"""tb_fornecedor_changes

Revision ID: 8e6249e37efa
Revises: 4060addae700
Create Date: 2026-03-02 14:01:34.268553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6249e37efa'
down_revision: Union[str, Sequence[str], None] = '4060addae700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_fornecedor',
                    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
                    sa.Column('razao', sa.String(length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=True),
                    sa.Column('cnpj', sa.String(length=14), nullable=True),
                    sa.Column('numero_tel', sa.String(
                        length=20), nullable=True),
                    sa.Column('cep', sa.String(length=8), nullable=True),
                    sa.Column('rua', sa.String(length=128), nullable=True),
                    sa.Column('numero_endereco', sa.Integer(), nullable=True),
                    sa.Column('cidade', sa.String(length=128), nullable=True),
                    sa.Column('uf', sa.String(length=2), nullable=True),
                    sa.Column('pais', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('fornecedor_id')
                    )

    # Migrate data from old table to new table
    op.execute("""
        INSERT INTO tb_fornecedor (fornecedor_id, razao, email, cnpj, numero_tel, cep, rua, numero_endereco, cidade, uf, pais)
        SELECT id, razao, email, cnpj, numero_tel, cep, rua, numero, cidade, uf, pais
        FROM supplier
    """)

    op.drop_table('supplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('razao', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=True),
                    sa.Column('cnpj', sa.VARCHAR(length=14),
                              autoincrement=False, nullable=True),
                    sa.Column('numero_tel', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('cep', sa.VARCHAR(length=8),
                              autoincrement=False, nullable=True),
                    sa.Column('rua', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=True),
                    sa.Column('numero', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('cidade', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=True),
                    sa.Column('uf', sa.VARCHAR(length=2),
                              autoincrement=False, nullable=True),
                    sa.Column('pais', sa.VARCHAR(length=64),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('supplier_pkey'))
                    )

    # Migrate data back from new table to old table
    op.execute("""
        INSERT INTO supplier (id, razao, email, cnpj, numero_tel, cep, rua, numero, cidade, uf, pais)
        SELECT fornecedor_id, razao, email, cnpj, numero_tel, cep, rua, numero_endereco, cidade, uf, pais
        FROM tb_fornecedor
    """)

    op.drop_table('tb_fornecedor')
    # ### end Alembic commands ###
